import React, { useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Input from '@/components/Auth/input'


const forget_password = () => {

    const [email, setEmail] = useState('')


    return (
        <>
            <Head>
                <title>Forgot Password- Rainbow Fingers</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <div className='w-full h-screen  flex '>
                {/* Left side */}
                <div className=' h-full w-full md:w-1/2  bg-[url("/images/forget_password.png")] bg-no-repeat bg-center bg-cover absolute md:relative -z-10 md:z-0 '>
                </div>
                {/* Right side */}
                <div className=' w-full h-screen md:w-1/2  '>
                    <Link href='/'>
                        <nav className='mt-3 md:mt-6' >
                            <img src="../images/logo.png" alt="Rainbow Fingers logo" className=' ' />
                        </nav>
                    </Link>
                    <div className='flex justify-center'>
                        <div className='bg-white/90 md:bg-transparent px-2 md:px-8 py-4 md:py-16 self-center mt-[30%] md:mt-[25%] w-4/5 lg:w-3/5  lg:max-w-md rounded-md '>
                            <h2 className='text-3xl md:text-4xl  md:mb-4 font-nunito font-bold leading-[40px] ' >
                                Forgot Password
                            </h2>
                            <p className='font-nunito font-normal text-[#6B6B6B] text-[16px] leading-[24px] -tracking-[2%] mt-4 '>Please fill in your email address, you will receive a link to reset your password</p>

                            <div className='flex flex-col gap-4 mt-12 md:mt-12'>

                                <Input
                                    label='Email address'
                                    id='email'
                                    onChange={(ev: any) => setEmail(ev.target.value)}
                                    value={email}
                                />
                            </div>
                            <button className="bg-[#DF3B11] py-2 md:py-4 text-white rounded-full w-full mt-8 hover:bg-opacity-80 transition font-nunito font-medium ">
                                Continue
                            </button>


                        </div>
                    </div>
                </div >
            </div >
        </>
    )
}

export default forget_password