import React from 'react'
import Head from 'next/head'


const Auth = () => {
  return (
    <>
      <Head>
        <title>Auth- Rainbow Fingers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full mx-auto'>
        sgs

      </div>
    </>
  )
}

export default Auth