import React, { useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Input from '@/components/Auth/input'


const Auth = () => {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')


  return (
    <>
      <Head>
        <title>Auth- Rainbow Fingers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full h-screen  flex '>
        {/* Left side */}
        <div className=' h-full w-full md:w-1/2  bg-[url("/images/sign_image.png")] bg-no-repeat bg-center bg-cover absolute md:relative -z-10 md:z-0 '>
        </div>
        {/* Right side */}
        <div className=' w-full md:w-1/2 '>
          <Link href='/'>
            <nav className='mt-[34px]' >
              <img src="images/logo.png" alt="Rainbow Fingers logo" className=' ' />
            </nav>
          </Link>
          <div className='flex justify-center'>
            <div className='bg-green-900/10 md:bg-transparent px-8 py-16 self-center mt-2 w-4/5 lg:w-3/5  lg:max-w-md rounded-md '>
              <h2 className='text-4xl mb-8 font-nunito font-bold' >
                Create an account
              </h2>
              <p className='text-xl font-medium font-nunito text-[#6B6B6B] '>Please fill in your email address</p>
              <div className='flex flex-col gap-4 mt-[50px]'>
                <Input
                  label='Email Address'
                  id='email'
                  onChange={(ev: any) => setEmail(ev.target.value)}
                  value={email}
                  type='email'
                />
                <Input
                  label='Password'
                  id='password'
                  onChange={(ev: any) => setPassword(ev.target.value)}
                  value={password}
                />
              </div>
              <button className="bg-[#DF3B11] py-4 text-white rounded-full w-full mt-10 hover:bg-opacity-80 transition ">
                Continue
              </button>
              
            </div>
          </div>
        </div >
      </div >
    </>
  )
}

export default Auth