import React from 'react'
import Head from 'next/head'
import Link from 'next/link'


const Auth = () => {
  return (
    <>
      <Head>
        <title>Auth- Rainbow Fingers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full h-screen  flex '>
        {/* Left side */}
        <div className=' h-full w-full md:w-1/2  bg-[url("/images/sign_image.png")] bg-no-repeat bg-center bg-cover absolute md:relative -z-10 md:z-0 '>
        </div>
        {/* Right side */}
        <div className=' w-full md:w-1/2 '>
          <Link href='/'>
            <nav className='mt-[34px]' >
              <img src="images/logo.png" alt="Rainbow Fingers logo" className=' ' />
            </nav>
          </Link>
          <div className='flex justify-center'>
            <div className='bg-green-900/10 md:bg-transparent px-16 py-16 self-center mt-2 w-4/5 md:w-4/5 lg:w-3/5  lg:max-w-md rounded-md '>

            </div>
            
          </div>
        </div >
      </div >
    </>
  )
}

export default Auth