import React, { useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Input from '@/components/Auth/input'

const EnterOtp = () => {

    const [otp, setOtp] = useState('')


    return (
        <>
            <Head>
                <title>Verify your account- Rainbow Fingers</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <div className='w-full h-screen  flex '>
                {/* Left side */}
                <div className=' h-full w-full md:w-1/2  bg-[url("/images/forget_password.png")] bg-no-repeat bg-center bg-cover absolute md:relative -z-10 md:z-0 '>
                </div>
                {/* Right side */}
                <div className=' w-full h-screen md:w-1/2  '>
                    <Link href='/'>
                        <nav className='mt-3 md:mt-6' >
                            <img src="../images/logo.png" alt="Rainbow Fingers logo" className=' ' />
                        </nav>
                    </Link>
                    <div className='flex justify-center'>
                        <div className='bg-white/90 md:bg-transparent px-2 md:px-8 py-4 md:py-16 self-center mt-[10%] w-4/5  lg:max-w-md rounded-md '>
                            <h2 className='text-3xl md:text-4xl  md:mb-4 font-nunito font-bold ' >
                                Check your email for a code
                            </h2>
                            <p className='font-nunito font-mediu text-[14px] md:text-[20px] leading-7 text-[#6B6B6B] mt-8 '>We sent a 6 character code to your email. The OTP code expires shortly</p>

                            <div className='flex flex-col gap-4 mt-8'>

                                <Input
                                    label='Enter 6-digit OTP'
                                    id='otp'
                                    onChange={(ev: any) => setOtp(ev.target.value)}
                                    value={otp}
                                />

                            </div>
                            <button className="bg-[#DF3B11] py-2 md:py-4 text-white rounded-full w-full mt-8 hover:bg-opacity-80 transition font-nunito font-medium ">
                                Continue
                            </button>
                            <p className='font-nunito font-medium text-[14px] md:text-[20px] leading-[20px] text-[#6B6B6B] mt-10 '>Can’t find your code? Check your spam folder!</p>

                            <div className='flex mt-20 md:mt-52 justify-between items-center font-nunito font-medium text-[14px] md:text-[20px] text-[#747474]   '>
                                <Link href='/' >
                                    <p>Privacy & Terms</p>
                                </Link>

                                <Link href='/'>
                                    <p>Contact us</p>
                                </Link>
                            </div>
                        </div>
                    </div>
                </div >
            </div >
        </>
    )
}

export default EnterOtp