import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Hero from '@/components/Hero'
import MiniReview from '@/components/MiniReview'
import Experience from '@/components/Experience'
import Discover from '@/components/Discover'
import Learn from '@/components/Learn'
import Instructors from '@/components/Instructors'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Rainbow Fingers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <MiniReview />
      <Experience />
      <Discover />
      <Learn />
      <Instructors />
      <Footer />
    </>
  )
}
