import Head from 'next/head'
import Hero from '@/components/Hero'
import MiniReview from '@/components/MiniReview'
import Experience from '@/components/Experience'
import Discover from '@/components/Discover'
import Learn from '@/components/Learn'
import Instructors from '@/components/Instructors'
import Footer from '@/components/Footer'
import Nav from '@/components/Nav'



export default function Home() {
  return (
    <div className='w-full'>
      <Head>
        <title>Rainbow Fingers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full mx-auto'>
        <Nav />
        <Hero />
        <MiniReview />
        <Experience />
        <Discover />
        <Learn />
        <Instructors />
        <Footer />
      </div>

    </div>
  )
}
