import React from 'react'
import Head from 'next/head'
import LessonNav from '@/components/LessonPage/LessonNav'
import LessonHero from '@/components/LessonPage/LessonHero'
import LessonDiscover from '@/components/LessonPage/LessonDiscover'
import LessonMain from '@/components/LessonPage/LessonMain'
import LessonGenre from '@/components/LessonPage/LessonGenre'
import LessonFooter from '@/components/LessonPage/LessonFooter'
import LessonAlbumSlide from '@/components/LessonPage/LessonAlbumSlide'

const Lessons = () => {
    return (
        <>
            <Head>
                <title>Lessons- Rainbow Fingers</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='w-full mx-auto'>
                <LessonNav />
                <LessonHero />
                <LessonDiscover />
                <LessonMain />
                <LessonGenre />
                <LessonAlbumSlide />
                <LessonFooter />

            </div>
        </>
    )
}

export default Lessons