import React from 'react'
import Head from 'next/head'
import LibraryNav from '@/components/LibraryPage/LibraryNav.jsx'
import LibraryHero from '@/components/LibraryPage/LibraryHero'
import LibraryCourses from '@/components/LibraryPage/LibraryCourses'
import LibraryFooter from '@/components/LibraryPage/LibraryFooter'



const Lessons = () => {
    return (
        <>
            <Head>
                <title>Library- Rainbow Fingers</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='w-full mx-auto'>
                <LibraryNav />
                <LibraryHero />
                <LibraryCourses />    
                <LibraryFooter />
            </div>
        </>
    )
}

export default Lessons