import { useCallback, useState } from 'react'
import axios from 'axios'
import Head from 'next/head'
import Link from 'next/link'
import Input from '@/components/Auth/input'
import { IoLogoGoogle, IoLogoApple } from 'react-icons/io';
import { signIn } from 'next-auth/react'
import { useRouter } from 'next/router'

const Login = () => {
  const router= useRouter();

  const [email, setEmail] = useState('');
  const [name, setName] = useState('');
  const [password, setPassword] = useState('');

  const [variant, setVariant] = useState('login');

  const toggleVariant = useCallback(() => {
    setVariant((currentVariant) =>
      currentVariant === 'login' ? 'register' : 'login');
  }, []);

  const login = useCallback(async () => {
    try {
      await signIn('credentials', {
        email,
        password,
        redirect: false,
        callbackUrl: '/',
      });

      router.push('/')
    } catch (error) {
      console.log(error);
    }
  }, [email, password, router])

  const register = useCallback(async () => {
    try {
      await axios.post('/api/register', {
        email,
        name,
        password
      });

      login();
    } catch (error) {
      console.log(error)
    }
  }, [email, name, password, login]);


  return (
    <>
      <Head>
        <title>Login- Rainbow Fingers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className='w-full h-full  flex  '>
        {/* Left side */}
        <div className={` w-full md:w-1/2  bg-[url(${variant === 'login' ? '"/images/forget_password.png"' : '"/images/alternate_hero.png"'})] bg-no-repeat bg-center bg-cover absolute md:relative -z-10 md:z-0 `}>
        </div>
        {/* Right side */}
        <div className=' w-full h-screen md:w-1/2  '>
          <Link href='/'>
            <nav className='mt-1 md:mt-2 ' >
              <img src="../images/logo.png" alt="Rainbow Fingers logo" className=' ' />
            </nav>
          </Link>
          <div className='flex justify-center'>
            <div className={`bg-${variant === 'login' ? 'green-900/10' : 'white/70 '} md:bg-transparent px-2 md:px-6 py-4 md:py-8 self-center mt-[4%] md:mt-[10%] w-4/5 lg:w-3/5 lg:max-w-md rounded-md`}>
              <h2 className='text-3xl md:text-4xl  md:mb-3 font-nunito font-bold' >
                {variant === 'login' ? 'Login' : 'Create an account'}
              </h2>

              <div className='flex flex-col gap-2 md:gap-4 mt-6 md:mt-9'>

                {variant === 'register' && (
                  <Input
                    id="name"
                    type="text"
                    label="Username"
                    value={name}
                    onChange={(e: any) => setName(e.target.value)}
                  />
                )}
                <Input
                  id="email"
                  type="email"
                  label="Email address or phone number"
                  value={email}
                  onChange={(e: any) => setEmail(e.target.value)}
                />
                <Input
                  type="password"
                  id="password"
                  label="Password"
                  value={password}
                  onChange={(e: any) => setPassword(e.target.value)}
                />
              </div>


              <button onClick={variant === 'login' ? login :register} className="bg-[#DF3B11] py-2 md:py-3 text-white rounded-full w-full mt-6 hover:bg-opacity-80 transition font-nunito font-medium ">
                {variant === 'login' ? 'Continue' : 'Sign up'}
              </button>


              <div className='mt-3 flex items-center justify-between text-[#6B6B6B] '>
                <hr className="w-[43%] " />
                <p className="font-hanken font-medium text-xl text-[#6B6B6B]" >Or</p>
                <hr className="w-[43%] " />
              </div>


              <button onClick={()=> signIn('google', {callbackUrl: '/' })} 
              className="border-solid border-[1px] border-[#DF3B11] py-2 md:py-3 text-white md:text-[#DF3B11] rounded-full w-full mt-4 hover:bg-opacity-80 transition flex items-center text-center bg-[#DF3B11] md:bg-transparent  ">
                <span className='mx-auto flex gap-4 '>
                  <IoLogoGoogle
                    size={24}
                  />
                  Continue with Google
                </span>
              </button>

              <div className=' mt-8 flex flex-col items-center '>
                <p className="text-gray-900 md:text-[#6B6B6B] font-nunito font-medium text-[16px] leading-[20px]">
                  {variant === 'login' ? 'Do not have an account?' : 'Already have an account?'}

                  <span onClick={toggleVariant} className=" text-gray-900 font-nunito font-medium ml-2 text-[16px] leading-[20px] hover:underline cursor-pointer mt-2 ">
                    {variant === 'login' ? 'Create an account.' : 'Sign in to an existing account.'}
                  </span>

                </p>

              </div>

            </div>
          </div>
        </div >
      </div >
    </>
  )
}

export default Login