import React from 'react'
import Head from 'next/head'
import ProductNav from '@/components/Productpage/ProductNav'
import ProductHero from '@/components/Productpage/ProductHero'
import ProductFooter from '@/components/Productpage/ProductFooter'
import ProductDeals from '@/components/Productpage/ProductDeals'
import ProductReview from '@/components/Productpage/ProductReview'
import ProductOffers from '@/components/Productpage/ProductOffers'

const Product = () => {
    return (
        <>
            <Head>
                <title>Products- Rainbow Fingers</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='w-full mx-auto'>
                <ProductNav />
                <ProductHero />
                <ProductDeals />
                <ProductOffers />
                <ProductReview />
                <ProductFooter />
            </div>
        </>
    )
}

export default Product