import React from 'react'
import Head from 'next/head'
import ProductLibraryNav from '@/components/ProductLibraryPage/ProductLibraryNav'
import ProductLibraryHero from '@/components/ProductLibraryPage/ProductLibraryHero'
import ProductLibraryOffers from '@/components/ProductLibraryPage/ProductLibraryOffers'
import ProductLibraryFooter from '@/components/ProductLibraryPage/ProductLibraryFooter'

const Productproductlibrary = () => {
  return (
    <>
      <Head>
        <title>Products- Rainbow Fingers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full mx-auto'>
        <ProductLibraryNav />
        <ProductLibraryHero />
        <ProductLibraryOffers />
        <ProductLibraryFooter />

      </div>
    </>
  )
}

export default Productproductlibrary