import React from 'react'
import Head from 'next/head'
import StoreNav from '@/components/StorePage/StoreNav.jsx'
import StoreHero from '@/components/StorePage/StoreHero'
import StoreCourses from '@/components/StorePage/StoreCourses'
import StoreFooter from '@/components/StorePage/StoreFooter'



const Lessons = () => {
    return (
        <>
            <Head>
                <title>Store- Rainbow Fingers</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='w-full mx-auto'>
                <StoreNav />
                <StoreHero />
                <StoreCourses />    
                <StoreFooter />
            </div>
        </>
    )
}

export default Lessons